USE DATABASE TRAINING_DATAMASTERS_DB
USE SCHEMA RL_SMAR959_SCHEMA;

CREATE OR REPLACE TABLE EMPLOYEE (
  ID_EMPLOYEE NUMBER PRIMARY KEY,
  NAM_EMPLOYEE VARCHAR(100),
  ID_DEPARTMENT NUMBER
);

CREATE OR REPLACE TABLE DEPARTMENT (
  ID_DEPARTMENT NUMBER PRIMARY KEY,
  NAM_DEPARTMENT VARCHAR(100)
);

CREATE OR REPLACE TABLE PROJECT (
  ID_PROJECT NUMBER PRIMARY KEY,
  NAM_PROJECT VARCHAR(100)
);

CREATE OR REPLACE TABLE EMPLOYEE_PROJECT (
  ID_EMPLOYEE NUMBER,
  ID_PROJECT NUMBER,
  PRIMARY KEY (ID_EMPLOYEE, ID_PROJECT)
);
